### ISSUE TITLE
ValueError: Response is None

### ISSUE THREAD

**Issue by yzl256** [carrotshub/ZhiHuSpider#1]
连接错误： 403 Client Error: Forbidden for url: https://www.zhihu.com/api/v4/questions/320078376/answers?include=data%5B*%5D.voteup_count,content&limit=20&offset=0&sort_by=voteups
Traceback (most recent call last):
  File "D:\code\ZhihuSpider-master\GrandConcourse.py", line 38, in <module>
    a = make_answers_as_book(question_id, warehouse)
  File "D:\code\ZhihuSpider-master\zhihu\question\__init__.py", line 110, in make_answers_as_book
    raise ValueError('Response is None')
ValueError: Response is None

**Comment by carrotshub** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已收到，我将尽快回复！谢谢！

**Comment by yzl256** [comment]
是知乎的API不对吗？大神这个报错要怎么解决
